bot:
  image:
    repository: asurov/crawler
    tag: latest
ui:
  image:
    repository: asurov/crawler-ui
    tag: latest
rabbitmq:
  rabbitmq:
      username: guest
      password: guest
mongodb:
  usePassword: false